version: '3.4'

x-logging: &logging
  options:
    max-size: '1b'
    labels: "{{.Name}}"
  driver: json-file

services:
  console: &console
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /dev:/dev
      - .:/app:cached
      - ~/.bash_history:/root/.bash_history
    working_dir: /app
    logging: *logging
    command: /bin/bash
